title: OrigiNathan
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Nathan Bryant
avatar: /logo.png
email: bryant.engineering@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page-:num/"
# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: innovate4fun
  card: summary
logo: logo.png
social:
  name: Nathan Bryant
  links:
    - https://twitter.com/innovate4fun
    - https://www.facebook.com/nathan.bryant.37
    - https://github.com/debrant
google_site_verification:
lang: en
